
[build] 
  publish = "public"
  command = "hugo --enableGitInfo --ignoreCache"

[context.production.environment]
  command = "hugo --enableGitInfo  --buildFuture --ignoreCache -b $DEPLOY_PRIME_URL"
  HUGO_VERSION = "0.67.1" # if older, use format: 0.53 (no trailing zero)
  HUGO_ENV = "production"
  HUGO_ENABLEGITINFO = "true"
  
[context.deploy-preview]
command = "hugo --enableGitInfo  --buildFuture --ignoreCache -b $DEPLOY_PRIME_URL"
HUGO_VERSION = "0.67.1"

[context.branch-deploy]
command = "hugo --enableGitInfo  --buildFuture --ignoreCache -b $DEPLOY_PRIME_URL"
HUGO_VERSION = "0.67.1" # if older, use format: 0.53 (no trailing zero)



