on: push

name: Render about me 

jobs:
  render:
    name: Render aboutme
    runs-on: macOS-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-r@v1
      - uses: r-lib/actions/setup-pandoc@v1
      
      - name: Install R packages
        run: |
          install.packages(c("rmarkdown","dplyr", "tidyr", "ggplot2", "scholar", "knitr"))
        shell: Rscript {0}
        
      - name: Render about me
        run: Rscript -e 'rmarkdown::render("content/aboutme/index.Rmd")'
        
      - name: Commit results
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git commit content/aboutme -m 'Re-build about me' || echo "No changes to commit"
          git push origin || echo "No changes to commit"
      #     
      # - name: Install npm
      #   uses: actions/setup-node@v1
      # 
      # - name: Deploy to Netlify
      #   # NETLIFY_AUTH_TOKEN and NETLIFY_SITE_ID added in the repo's secrets
      #   env:
      #     NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
      #     NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
      #   run: |
      #     npm install netlify-cli -g
      #     netlify deploy --prod
